stages:
  - build
  - test
  - deploy

image: 'maven:3.8.1-openjdk-17-slim'

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode --errors --fail-at-end --show-version --no-transfer-progress
    -DinstallAtEnd=true -DdeployAtEnd=true

cache:
  paths:
    - .m2/repository

nevia-booking-reminder-build:
  stage: build
  script:
    - cd nevia-booking-reminder
    - mvn clean install -Dmaven.test.skip=true
  artifacts:
    paths:
      - nevia-booking-reminder/target/*.jar
  tags:
    - runner-jack

nevia-booking-reminder-test:
  stage: test
  needs: ["nevia-booking-reminder-build"]
  script:
    - cd nevia-booking-reminder
    - mvn clean
  tags:
    - runner-jack

nevia-booking-reminder-deploy:
  stage: deploy
  needs: ["nevia-booking-reminder-test"]
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'    
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY_NOTIFICATION_INT"
    - echo "$SSH_KEY_NOTIFICATION_INT" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan 192.168.3.21 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp -o StrictHostKeyChecking=no /builds/cloudbuildings/nevia/.m2/repository/com/example/nevia-booking-reminder/1.0.0-RELEASE/nevia-booking-reminder-1.0.0-RELEASE.jar toto@192.168.3.21:/tmp
    - ssh -o StrictHostKeyChecking=no -tt toto@192.168.3.21 'sudo sh /opt/nevia/scripts/nevia-booking-reminder-deployement.sh'
  tags:
    - runner-jack
