eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.2:8761/eureka

dispatcher:
  ribbon:
    listOfServers: http://192.168.1.5:8080/, http://192.168.1.7:8080/


notification-manager-service:
  ribbon:
    listOfServers: http://192.168.1.5:9877/
