spring:
  datasource:
    url: jdbc:postgresql://192.168.1.15:5432/neviardb
    username: postgres
    password: toto

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.2:8761/eureka

